library(multtest)
if(!require(multtest))install.packages("multtest")
if(!require(Seurat))install.packages("Seurat")
if(!require(dplyr))install.packages("dplyr")
if(!require(mindr))install.packages("mindr")
if(!require(mindr))install.packages("tidyverse")
library("ggplot2")
rm(list = ls())

expr <- read.table("RawCounts.txt", sep="\t", header=T, row.names=1)
rownames(expr) <- paste(paste("D",substring(expr$orig.ident,4),sep = ""),rownames(expr),sep = "_")
expr <- expr[,-c(1:4)]
expr <- t(expr)

pbmc <- CreateSeuratObject(counts = expr,min.cells = 3,min.features = 500)
ncol(pbmc)
nrow(pbmc)

if(!require(patchwork))install.packages("patchwork")
if(!require(R.utils))install.packages("R.utils")
pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-") 
pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 6000 & percent.mt < 5)   
pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc <- ScaleData(pbmc, features = rownames(pbmc))
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
pbmc <- JackStraw(pbmc, num.replicate = 100)
pbmc <- ScoreJackStraw(pbmc, dims = 1:20)
JackStrawPlot(pbmc, dims = 1:20)
ElbowPlot(pbmc) 
pbmc <- FindNeighbors(pbmc, dims = 1:15)
pbmc <- FindClusters(pbmc, resolution = 0.5)
pbmc <- RunUMAP(pbmc, dims = 1:15)
DimPlot(pbmc, reduction = "umap",label = TRUE)

new.cluster.ids <- c(  "TELCs","TELCs","VCT like cell","VCT like cell","VCT like cell","TELCs","VCT like cell","TELCs","TELCs","unknown")
names(new.cluster.ids) <- levels(pbmc)
pbmc <- RenameIdents(pbmc, new.cluster.ids)
pbmc@active.ident<-factor(x=pbmc@active.ident,levels=c("TELCs","VCT like cell","unknown"))
pbmc@meta.data$cells<-factor(x=pbmc@active.ident,levels=c("TELCs","VCT like cell","unknown"))
DimPlot(pbmc, reduction = "umap", label = TRUE, pt.size = 0.5)
saveRDS(pbmc,"pbmc.rds")